apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:  # Defines a container inside the Pod, named secret-demo-container using the Nginx image.
  containers:
  - name: secret-demo-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
    volumeMounts:  # Mounts a volume named secret-volume inside the container at etc/secret-volume.
     - name: secret-volume
       mountPath: "etc/secret-volume"
       readOnly: true
  volumes:  # Creates a volume named secret-volume.
  - name: secret-volume
    secret:
      secretName: my-secret
